import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import CustomCursor from "@/components/ui/customCursor/CustomCursor";
import Layout from "@/components/layout/Layout";

const audioWideSans = localFont({
  src: "./fonts/Audiowide-Regular.ttf",
  variable: "--font-Audiowide-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${audioWideSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout>{children}</Layout>
        <CustomCursor/>
      </body>
    </html>
  );
}
